const HubCategories = [
    "Anime and Manga",
    "Art",
    "Books",
    "Business",
    "Cars and Motor Vehicles",
    "Crafts and DIY",
    "Education",
    "Fashion",
    "Finance",
    "Fitness",
    "Food",
    "Gaming",
    "Health",
    "History",
    "Memes",
    "Movies and TV Series",
    "Music",
    "Pets",
    "Photography",
    "Programming",
    "Science",
    "Streamers",
    "Sports",
    "Technology",
    "Travel",
];

export default HubCategories;