version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8800:8800"
    environment:
      - MONGO=${MONGO}
    depends_on:
      - mongo
    restart: unless-stopped


  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:8800
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
